//
//  FindPasswordWorker.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/11.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FindPasswordWorker {
    func findPassword(request: FindPassword.FindPassword.Request, completion: @escaping () -> Void) {
        AuthAPI.shared.findPassword(email: request.email) { (response) in
            switch response {
            case .success():
                completion()
            case let .failure(error):
                completion()
            }
        }
    }
}
