//
//  FindPasswordWorker.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/11.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FindPasswordWorker {
    func findPassword(request: FindPassword.FindPassword.Request, completion: @escaping (FindPassword.FindPassword.Response) -> Void) {
        AuthAPI.shared.findPassword(email: request.email) { (response) in
            switch response {
            case let .success(value):
                if value.success, let data = value.data {
                    let response = FindPassword.FindPassword.Response(request: request, data: data)
                    completion(response)
                } else {
                    let response = FindPassword.FindPassword.Response(request: request, error: .server(value.message))
                    completion(response)
                }
            case let .failure(error):
                let response = FindPassword.FindPassword.Response(request: request, error: .error(error))
                completion(response)
            }
        }
    }
}
