//
//  ChallengeModels.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/10/26.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Challenge {
    
    // MARK: Use cases
    
    enum Something {
        struct Request { }
        struct Response { }
        struct ViewModel { }
    }
    
    struct User {
        var id: Int
        var email: String
        var nickname: String
        var score: Int
    }
    
    struct ViewModel {
        var members: [Player]
    }
    
    struct RankCellViewModel {
        var id: Int
        var email: String
        var rank: Int
        var nickname: String
        var score: Int
    }

}
