//
//  ResetPasswordInteractor.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/13.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResetPasswordBusinessLogic {
    func resetPassword(request: ResetPassword.ResetPassword.Request)
}

protocol ResetPasswordDataStore {
    var uid: String! { get set }
    var token: String! { get set }
}

class ResetPasswordInteractor: ResetPasswordBusinessLogic, ResetPasswordDataStore {
    var presenter: ResetPasswordPresentationLogic?
    var worker = ResetPasswordWorker()
    var uid: String!
    var token: String!
    
    func resetPassword(request: ResetPassword.ResetPassword.Request) {
        self.worker.findPassword(request: request, uid: uid, token: token) { [weak self] (response) in
            self?.presenter?.presentResetPassword(response: response)
        }
    }
}
