//
//  ResetPasswordModels.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/13.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ResetPassword {
    // MARK: Use cases
    
    enum UseCase {
        case ResetPassword(ResetPassword.Request)
    }
    
    enum ResetPassword{
        struct Request{
            var password1: String
            var password2: String
        }
        
        struct Response {
            var request: Request
            var response: ResetPasswordResponse?
            var error: Common.CommonError?
        }
        
        struct ViewModel {
            var detail: String?
        }
    }
}
