//
//  SplashPresenter.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/11/24.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
    func presentCheckLogin(response: Splash.CheckLogin.Response)
}

class SplashPresenter: SplashPresentationLogic {
    weak var viewController: SplashDisplayLogic?
    func presentCheckLogin(response: Splash.CheckLogin.Response) {
        if response.isLogined{
            self.viewController?.displayLogined()
        } else {
            self.viewController?.displayNotLogined()
        }
    }
}
