//
//  SplashWorker.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/11/24.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SplashWorker {
  private let pushManager = PushManager()
  
    func setPushNotification(completion: @escaping () -> Void){
    pushManager.getPushStatus { status in
      switch status{
      case .authorized:
        completion()
      case .denied:
        completion()
      case .notDetermined:
        self.pushManager.registPushNotification { granted in
          if granted {
            DispatchQueue.main.async {
              UIApplication.shared.registerForRemoteNotifications()
                completion()
            }
          } else {
            completion()
          }
        }
      default:
        completion()
      }
    }
    
  }
}
