//
//  LoginRouter.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/05.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToSplash()
    func routeToRegistration()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    func routeToSplash() {
        if let delegate = UIApplication.shared.delegate as? AppDelegate {
            delegate.window?.rootViewController = SplashViewController()
            delegate.window?.makeKeyAndVisible()
        }
    }
    
    func routeToRegistration() {
        let destinationVC = RegistrationViewController()
        navigateToRegistration(source: viewController!, destination: destinationVC)
    }
    
    func navigateToRegistration(source: LoginViewController, destination: RegistrationViewController){
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
}
