//
//  RegistrationWorker.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/05.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegistrationWorker {
    func validateAccount(text: String) -> Bool{
        return text.count >= 1
    }
    
    func validatePassword(text: String) -> Bool{
        return text.count >= 8 && text.count <= 20
    }
    
    func validateNickname(text: String) -> Bool{
        return text.count >= 1
    }
    
    func registration(request: Registration.Registration.Request, completion: @escaping (Registration.Registration.Response) -> Void){
        AuthAPI.shared.registration(email: request.email, password1: request.password1, password2: request.password2) { (response) in
            switch response {
            case let .success(value):
                AuthManager.shared.userToken = value.token
                AuthManager.shared.user = value.user
                DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                    if let uid = value.user?.id{
                        AuthAPI.shared.setNickname(uid: uid, nickname: request.nickname)
                        AuthAPI.shared.initQuest()
                    }
                }
                
                let response = Registration.Registration.Response(request: request, response: value)
                completion(response)
            case let .failure(error):
                let response = Registration.Registration.Response(request: request, error: .error(error))
                completion(response)
            }
        }
    }
    
}
