//
//  RegistrationInteractor.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/12/05.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationBusinessLogic {
    func validateAccount(request: Registration.ValidateAccount.Request)
    func validatePassword(request: Registration.ValidatePassword.Request)
    func validatePasswordConfirm(request: Registration.ValidatePasswordConfirm.Request)
}

protocol RegistrationDataStore {
    //var name: String { get set }
}

class RegistrationInteractor: RegistrationBusinessLogic, RegistrationDataStore {
    var presenter: RegistrationPresentationLogic?
    var worker = RegistrationWorker()
    //var name: String = ""
    func validateAccount(request: Registration.ValidateAccount.Request){
        let text = request.account
        let result = worker.validateAccount(text: text)
        presenter?.presentValidateAccount(response: .init(isValid: result))
    }
    
    func validatePassword(request: Registration.ValidatePassword.Request){
        let text = request.password
        let result = worker.validatePassword(text: text)
        presenter?.presentValidatePassword(response: .init(isValid: result))
    }
    
    func validatePasswordConfirm(request: Registration.ValidatePasswordConfirm.Request){
        let text = request.password
        let result = worker.validatePassword(text: text)
        presenter?.presentValidatePasswordConfirm(response: .init(isValid: result))
    }
}
