//
//  PloggingRecordInteractor.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/10/22.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PloggingRecordBusinessLogic {
    func fetchRecord()
}

protocol PloggingRecordDataStore {
    var ploggingData: PloggingData? { get set }
}

class PloggingRecordInteractor: PloggingRecordBusinessLogic, PloggingRecordDataStore {
    var ploggingData: PloggingData?
    
    var presenter: PloggingRecordPresentationLogic?
    var worker: PloggingRecordWorker?
    
    func fetchRecord() {
        guard let ploggingData = self.ploggingData else { return }
        let response = PloggingRecord.FetchRecord.Response(ploggingData: ploggingData)
        self.presenter?.presentFetchRecord(response: response)
    }
}
