//
//  PloggingRecordPresenter.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/10/22.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PloggingRecordPresentationLogic {
    func presentFetchRecord(response: PloggingRecord.FetchRecord.Response)
}

class PloggingRecordPresenter: PloggingRecordPresentationLogic {
    weak var viewController: PloggingRecordDisplayLogic?
    
    func presentFetchRecord(response: PloggingRecord.FetchRecord.Response) {
        let distance = FormatDisplay.distance(response.ploggingData.distance)
        let timeSet = response.ploggingData.timeSet()
        let time = "\(String(format: "%02d", timeSet.minutes)):\(String(format: "%02d", timeSet.seconds))"
        
        let viewModel = PloggingRecord.FetchRecord.ViewModel(distance: distance, time: time)
        
        self.viewController?.displayFetchRecord(viewModel: viewModel)
    }
}
