//
//  PloggingRecordInteractor.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/10/22.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PloggingRecordBusinessLogic {
  
}

protocol PloggingRecordDataStore {
  
}

class PloggingRecordInteractor: PloggingRecordBusinessLogic, PloggingRecordDataStore {
  var presenter: PloggingRecordPresentationLogic?
  var worker: PloggingRecordWorker?
  //var name: String = ""
  
}
