//
//  ShareInteractor.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/09/29.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShareBusinessLogic {
    func doSomething(request: Share.Something.Request)
}

protocol ShareDataStore {
  //var name: String { get set }
}

class ShareInteractor: ShareBusinessLogic, ShareDataStore {
    var presenter: SharePresentationLogic?
    var worker: ShareWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func doSomething(request: Share.Something.Request) {
        worker = ShareWorker()
        worker?.doSomeWork()

        let response = Share.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
