//
//  ShareInteractor.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/09/29.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShareBusinessLogic {
    func fetchRecord()
    func shareToInstagram(assetIdentifier: String)
}

protocol ShareDataStore {
    var distance: Measurement<UnitLength>? { get set }
    var seconds: Int? { get set }
    var minutes: Int? { get set }
}

class ShareInteractor: ShareBusinessLogic, ShareDataStore {
    var distance: Measurement<UnitLength>?
    var seconds: Int?
    var minutes: Int?
    
    var presenter: SharePresentationLogic?
    var worker: ShareWorker?
    
    func fetchRecord() {
        guard let distance = self.distance,
              let seconds = self.seconds,
              let minutes = self.minutes
        else { return }
        let response = Share.FetchRecord.Response(distance: distance, seconds: seconds, minutes: minutes)
        presenter?.presentFetchRecord(response: response)
    }
    
    func shareToInstagram(assetIdentifier: String) {
        guard let url = URL(string: "instagram://library?LocalIdentifier=\(assetIdentifier)") else { return }
        DispatchQueue.main.async {
            if UIApplication.shared.canOpenURL(url) {
                UIApplication.shared.open(url)
            } else {
                print("Instagram is not installed")
            }
        }
    }
}
