//
//  SharePresenter.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/09/29.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SharePresentationLogic {
    func presentFetchRecord(response: Share.FetchRecord.Response)
}

class SharePresenter: SharePresentationLogic {
    weak var viewController: ShareDisplayLogic?
  
    // MARK: Do something
  
    func presentFetchRecord(response: Share.FetchRecord.Response) {
        guard let feed = response.feed, response.error == nil else {
            self.viewController?.displayError(error: response.error!, useCase: .FetchRecord)
            return
        }
        let data = response.ploggingData
        let timeSet = data.timeSet()
        let distance = FormatDisplay.distance(data.distance)
        var minutes = timeSet.minutes
        let seconds = timeSet.seconds
        var time = ""
        if minutes >= 60 {
            let hours = minutes / 60
            minutes = minutes % 60
            time = String(format: "%02d:%02d:%02d", hours, minutes, seconds)
        } else {
            time = String(format: "%02d:%02d", minutes, seconds)
        }
        
        let viewModel = Share.FetchRecord.ViewModel(distance: distance, time: time, image: response.image)
        
        self.viewController?.displayFetchRecord(viewModel: viewModel)
    }
}
