//
//  SharePresenter.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/09/29.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SharePresentationLogic {
    func presentSomething(response: Share.Something.Response)
}

class SharePresenter: SharePresentationLogic {
    weak var viewController: ShareDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: Share.Something.Response) {
    let viewModel = Share.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
    }
}
