//
//  ShareModels.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/09/29.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Share
{
  // MARK: Use cases
  
    enum FetchRecord{
        struct Response{
            var ploggingData: PloggingData
            var image: UIImage
        }
        
        struct ViewModel{
            var distance: String
            var time: String
            var image: UIImage
        }
    }
    
    enum UploadRecord{
    }
}
