//
//  ChallengeViewController.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/10/26.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit
import Then

protocol ChallengeDisplayLogic: class {
    func displaySomething(viewModel: Challenge.Something.ViewModel)
}

class ChallengeViewController: UIViewController, ChallengeDisplayLogic {
    var interactor: ChallengeBusinessLogic?
    var router: (NSObjectProtocol & ChallengeRoutingLogic & ChallengeDataPassing)?
    
    lazy var weekLabel = UILabel().then {
        $0.text = "10월 2주차"
        $0.textAlignment = .center
    }
    lazy var firstRankView = TopRankView()
    lazy var secondRankView = TopRankView()
    lazy var thirdRankView = TopRankView()
    lazy var rankTableView = UITableView().then {
        $0.backgroundColor = .blue
    }

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
  // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = ChallengeInteractor()
        let presenter = ChallengePresenter()
        let router = ChallengeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpView()
        setUpLayout()
    }
  
    func displaySomething(viewModel: Challenge.Something.ViewModel) {
    
    }
}
