//
//  ChallengeInteractor.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/10/26.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChallengeBusinessLogic {
    func getRandomName(num: Int) -> [String]
}

protocol ChallengeDataStore {
 
}

class ChallengeInteractor: ChallengeBusinessLogic, ChallengeDataStore {
    var presenter: ChallengePresentationLogic?
    var worker: ChallengeWorker?
    
    let names = [["천", "송", "이", "이", "최", "손", "고"],
                 ["승", "윤", "주", "서", "철", "병", "세"],
                 ["연", "서", "형", "영", "웅", "근", "림"]]
    
    func getRandomName(num: Int) -> [String] {
        var list = [String]()
        for _ in (0..<num) {
            var name = ""
            for index in (0...2) { name += names[index][Int.random(in: (0...6))] }
            list.append(name)
        }
        return list
    }
    
    func setRank(members: [Challenge.User]) -> [Int] {
        var rankList = [Int]()
        var currentScore = 0
        var currentRank = -1
        members.forEach { (user) in
            if user.score == currentScore {
                rankList.append(currentRank)
            } else {
                rankList.append(currentRank + 1)
                currentScore = user.score
                currentRank += 1
            }
        }
        return rankList
    }
}
