//
//  ChallengePresenter.swift
//  UniPlogger
//
//  Created by 바보세림이 on 2020/10/26.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChallengePresentationLogic
{
  func presentSomething(response: Challenge.Something.Response)
}

class ChallengePresenter: ChallengePresentationLogic
{
  weak var viewController: ChallengeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Challenge.Something.Response)
  {
    let viewModel = Challenge.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
