//
//  PloggingModels.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/09/27.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation
enum Plogging {
    // MARK: Use cases
    
    enum UseCase {
        
    }
    
    enum State {
        case ready
        case doing
        case pause
    }
    
    enum ChangeState {
        struct Request{
            var state: State
        }
    }
    
    enum Location{
      struct Response{
        var status: CLAuthorizationStatus
      }
    }
}
