//
//  PloggingPresenter.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/09/27.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation
protocol PloggingPresentationLogic {
    func presentDoing()
    func presentPause()
    func presentLocationService(response: Plogging.LocationAuth.Response)
    func presentStartRun(response: Plogging.StartRun.Response)
}

class PloggingPresenter: PloggingPresentationLogic {
    weak var viewController: PloggingDisplayLogic?
    func presentDoing() {
        viewController?.displayStart()
    }
    func presentPause() {
        viewController?.displayPause()
    }
    
    var coordinate: CLLocationCoordinate2D {
        return UserDefaults.standard.location
    }
    
    func presentLocationService(response: Plogging.LocationAuth.Response) {
      
        switch response.status{
        case .denied:
            guard let url = URL(string: UIApplication.openSettingsURLString) else { return }
            viewController?.displaySetting(message: "설정에서 위치 권한을 허용해주세요", url: url)    
        case .notDetermined, .restricted:
            guard let url = URL(string: "App-Prefs:root=Privacy&path=LOCATION") else { return }
            viewController?.displaySetting(message: "설정에서 위치 권한을 허용해주세요", url: url)
        case .authorizedWhenInUse, .authorizedAlways:
            viewController?.displayLocation(location: coordinate)
        default:
          break
        }
      
    }
    func presentStartRun(response: Plogging.StartRun.Response) {
        let viewModel = Plogging.StartRun.ViewModel(
            distance: FormatDisplay.distance(response.distance),
            location: response.location
        )
        
        viewController?.displayRun(viewModel: viewModel)
    }
    
    
}
