//
//  LogModels.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/11/21.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Log {
    // MARK: Use cases
    
    enum UseCase {
        case GetFeed
    }
    
    enum GetFeed{
        struct Response{
            var user: User?
            var feedList: [Feed]?
            var error: Common.CommonError?
        }
        
        struct ViewModel{
            var user: User
            var feedList: [Feed]
        }
    }
    
}
