//
//  LogRouter.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/11/21.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LogRoutingLogic {
    func routeToDetail()
}

protocol LogDataPassing {
    var dataStore: LogDataStore? { get }
}

class LogRouter: NSObject, LogRoutingLogic, LogDataPassing {
    weak var viewController: LogViewController?
    var dataStore: LogDataStore?
    
    func routeToDetail() {
        let destinationVC = DetailViewController()
        var destinationDS = destinationVC.router!.dataStore!
        
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
    }
    
    func navigateToDetail(source: LogViewController, destination: DetailViewController){
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToDetail(source: LogDataStore, destination: inout DetailDataStore){
        if let selectedIndexPath = viewController?.collectionView.indexPathsForSelectedItems?.first {
            destination.feed = viewController?.feedList[selectedIndexPath.item]
        }
    }

}
