//
//  LogWorker.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/11/21.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LogWorker {
    func getFeed(completion: @escaping(Log.GetFeed.Response) -> Void){
        guard let user = AuthManager.shared.user else { return }
        let uid = user.id
        LogAPI.shared.getFeed(uid: uid) { (response) in
            switch response{
            case let .success(feedList):
                let response = Log.GetFeed.Response(user: user,feedList: feedList)
                completion(response)
            case let .failure(error):
                let response = Log.GetFeed.Response(error: .error(error))
                completion(response)
            }
        }
    }
}
