//
//  LogWorker.swift
//  UniPlogger
//
//  Created by 손병근 on 2020/11/21.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LogWorker {
    //title
    //distance xx.xx
    //time int
    //uid
    //image
    func uploadRecord(){
        guard let uid = AuthManager.shared.user?.id else { return }
        let title = "testFeed"
        let distance = 10.15
        let time = 1000
        let image = UIImage(named: "img_logSample1")!
        
        PloggingAPI.shared.uploadRecord(uid: uid, title: title, distance: distance, time: time, image: image) { (result) in
            print(result)
        }
    }
}
